[book]
authors = ["sitandr"]
language = "en"
title = "Example book about Typst"

[preprocessor.typst-highlight]
# disable_inline = true
typst_default = true
render = true
warn_not_specified = true

# Uncomment the following line when developing
# command = "cargo run --release"

[output.html.code.hidelines]
typst = "% "
